import { Voice } from '@/types';

export const PRESET_VOICES: Voice[] = [
  {
    id: '冰糖',
    name: '冰糖',
    language: 'zh',
    gender: 'female',
    style: '活泼少女',
    previewText: '你好，我是冰糖。今天的声音会轻快一点，像把好消息递到你面前。',
    previewContext: '轻快、明亮、带一点少女感，语速中等。',
  },
  {
    id: '茉莉',
    name: '茉莉',
    language: 'zh',
    gender: 'female',
    style: '知性女声',
    previewText: '你好，我是茉莉。接下来我会用稳定清晰的语气，为你朗读这段内容。',
    previewContext: '知性、清楚、温和，适合说明和旁白。',
  },
  {
    id: '苏打',
    name: '苏打',
    language: 'zh',
    gender: 'male',
    style: '阳光少年',
    previewText: '你好，我是苏打。让我们把这句话读得更自然，也更有朝气。',
    previewContext: '阳光、轻松、少年感，语气自然。',
  },
  {
    id: '白桦',
    name: '白桦',
    language: 'zh',
    gender: 'male',
    style: '成熟男声',
    previewText: '你好，我是白桦。我会用沉稳的节奏，把信息讲得可靠而清楚。',
    previewContext: '成熟、稳重、有可信度，语速略慢。',
  },
  {
    id: 'Mia',
    name: 'Mia',
    language: 'en',
    gender: 'female',
    style: 'Lively girl',
    previewText: "Hi, I'm Mia. I can make this sentence sound bright, friendly, and full of energy.",
    previewContext: 'Bright, lively, and friendly. Medium pace.',
  },
  {
    id: 'Chloe',
    name: 'Chloe',
    language: 'en',
    gender: 'female',
    style: 'Sweet Dreamy',
    previewText: "Hi, I'm Chloe. This preview is soft, calm, and a little dreamy.",
    previewContext: 'Soft, sweet, dreamy, and gentle.',
  },
  {
    id: 'Milo',
    name: 'Milo',
    language: 'en',
    gender: 'male',
    style: 'Sunny boy',
    previewText: "Hi, I'm Milo. I can read this line with a clear and sunny tone.",
    previewContext: 'Sunny, youthful, clear, and relaxed.',
  },
  {
    id: 'Dean',
    name: 'Dean',
    language: 'en',
    gender: 'male',
    style: 'Steady Gentle',
    previewText: "Hi, I'm Dean. I will keep the delivery steady, gentle, and easy to follow.",
    previewContext: 'Steady, gentle, mature, and calm.',
  },
];
